"""Input discovery with a frozen, symlink-safe candidate set.

The candidate set for a batch run is resolved *before* anything is written:

* every entry is reduced to its canonical real path (symlinks followed), so
  links that point outside the input tree, links that form loops, and
  different names mapping to the same file are all detected explicitly;
* files the pipeline itself will (re)generate - output images and the batch
  report - are recognised even on a *first* re-run, so repeated runs with
  the same arguments never grow the pending set;
* each accepted candidate remembers its size/mtime fingerprint, which lets
  the executor reject a file that changed between discovery and processing
  instead of silently processing the wrong version.
"""
import errno
import os
import stat
from dataclasses import dataclass, field
from typing import List, Optional, Set, Tuple

from .image_io import SUPPORTED_EXTENSIONS
from .types import SkippedItem

REPORT_FILENAME = 'batch_report.json'

_FORMAT_TO_EXT = {
    'PNG': '.png', 'JPEG': '.jpg', 'BMP': '.bmp',
    'TIFF': '.tif', 'WEBP': '.webp',
}


@dataclass
class Candidate:
    """One frozen input candidate."""
    path: str                 # canonical real path (opened for reading)
    display_path: str         # path as discovered (for messages)
    rel_path: str             # path relative to the input root (POSIX style)
    size: int = 0
    mtime_ns: int = 0
    dev: int = 0
    ino: int = 0

    def fingerprint(self) -> Tuple[int, int, int, int]:
        return (self.dev, self.ino, self.size, self.mtime_ns)


@dataclass
class DiscoveryResult:
    candidates: List[Candidate] = field(default_factory=list)
    skipped: List[SkippedItem] = field(default_factory=list)

    @property
    def candidate_paths(self) -> List[str]:
        return [c.path for c in self.candidates]


def is_under(path: str, root: str) -> bool:
    """True if *path* is *root* itself or located below it."""
    if path == root:
        return True
    return path.startswith(root.rstrip(os.sep) + os.sep)


def _rel(path: str, root: str) -> str:
    return os.path.relpath(path, root).replace(os.sep, '/')


def planned_output_names(input_filename: str, output_specs: List[dict]) -> Set[str]:
    """Filenames the configured output nodes will generate for one input."""
    stem, ext = os.path.splitext(input_filename)
    names: Set[str] = set()
    for spec in output_specs:
        suffix = str(spec.get('suffix') or '')
        fmt = spec.get('format')
        if fmt:
            out_ext = _FORMAT_TO_EXT.get(str(fmt).upper(), ext or '.png')
        else:
            out_ext = ext or '.png'
        names.add('{}{}{}'.format(stem, suffix, out_ext))
    return names


def _resolve_input_root(path: str) -> str:
    """Canonical real path of the input directory."""
    real = os.path.realpath(path)
    if not os.path.exists(real):
        raise FileNotFoundError(f"Input directory does not exist: '{path}'")
    if not os.path.isdir(real):
        raise NotADirectoryError(f"Input path is not a directory: '{path}'")
    return real


def discover_inputs(input_dir: str, output_dir: str,
                    output_specs: Optional[List[dict]] = None) -> DiscoveryResult:
    """Freeze the candidate set for a batch run.

    The scan is non-recursive and examines only the top level of
    *input_dir*, preserving the previous behaviour for normal, separated
    directories.  Symlinks are resolved defensively (without letting the
    scan escape the directory) and each canonical file is classified once.
    """
    result = DiscoveryResult()
    output_specs = output_specs or []

    input_real = _resolve_input_root(input_dir)
    # Output may not exist yet; realpath still resolves existing parent links.
    output_real = os.path.realpath(output_dir)

    try:
        names = sorted(os.listdir(input_real))
    except OSError as e:
        raise FileNotFoundError(f"Cannot read input directory '{input_real}': {e}")

    image_names = []
    for name in names:
        ext = os.path.splitext(name)[1].lower()
        if ext in SUPPORTED_EXTENSIONS:
            image_names.append(name)
        elif name == REPORT_FILENAME:
            # The report this run writes must never be treated as input.
            if is_under(os.path.realpath(os.path.join(input_real, name)), output_real):
                result.skipped.append(SkippedItem(name, 'batch report generated by this pipeline'))

    # Everything this configuration can possibly write this run.
    planned: Set[str] = set()
    for n in image_names:
        planned.update(planned_output_names(n, output_specs))

    seen_entities: Set[Tuple[int, int]] = set()

    # Regular names first so a file itself, rather than a link to it, is the
    # accepted candidate; links mapping to the same entity are then skipped.
    def _scan_order(name: str):
        full = os.path.join(input_real, name)
        try:
            is_link = stat.S_ISLNK(os.lstat(full).st_mode)
        except OSError:
            is_link = False
        return (1 if is_link else 0, name)

    for name in sorted(image_names, key=_scan_order):
        display = os.path.join(input_dir, name)
        rel = name

        def skip(reason: str, detail: str = '') -> None:
            result.skipped.append(SkippedItem(rel, reason, detail))

        # lstat does not follow links: a looping link can never raise here.
        try:
            lst = os.lstat(os.path.join(input_real, name))
        except OSError as e:
            skip('unreadable entry', str(e))
            continue
        is_link = stat.S_ISLNK(lst.st_mode)
        link_target: Optional[str] = None
        if is_link:
            try:
                link_target = os.readlink(os.path.join(input_real, name))
            except OSError:
                link_target = None

        # Follow the link explicitly so loops/broken links are classified
        # instead of aborting (or escaping) the scan.
        try:
            st = os.stat(os.path.join(input_real, name))
        except OSError as e:
            if not is_link:
                skip('unreadable file', str(e))
            elif e.errno == errno.ELOOP:
                skip('symlink loop', f'target: {link_target or "?"}')
            else:
                skip('broken or unreadable symlink',
                     f'target: {link_target or "?"} ({e.strerror or e})')
            continue

        real = os.path.realpath(os.path.join(input_real, name))

        if not stat.S_ISREG(st.st_mode):
            if is_link:
                skip('symlink target is not a regular file',
                     f'target: {link_target or real}')
            continue

        # A link/hardlink to something this run will (re)write is classified
        # before the "outside" rule, so the operator sees the real cause.
        base = os.path.basename(real)
        if is_under(real, output_real):
            if base == REPORT_FILENAME:
                skip('batch report generated by this pipeline')
                continue
            if base in planned:
                skip('output file generated by this pipeline '
                     '(resolves into the output directory)')
                continue

        # Link escapes the input tree.
        if is_link and not is_under(real, input_real):
            skip('symlink points outside the input directory',
                 f'target: {link_target or real}')
            continue

        # Several names mapping to the same entity (hardlink / symlink).
        entity = (st.st_dev, st.st_ino)
        if entity in seen_entities:
            skip('already included via another name (same file)',
                 f'resolves to: {_rel(real, input_real)}')
            continue
        seen_entities.add(entity)

        result.candidates.append(Candidate(
            path=real,
            display_path=display,
            rel_path=_rel(real, input_real) if is_under(real, input_real) else rel,
            size=st.st_size,
            mtime_ns=st.st_mtime_ns,
            dev=st.st_dev,
            ino=st.st_ino,
        ))

    return result
